name = "data-drills-cf"
main = "dist/_worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat_v2"]

[vars]
VITE_BASE_URL = "https://drills.shibaleo.uk"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "10aa89de790d4ad8b16c0d24b023c365"

[assets]
directory = "dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
